####NUMPY AVANZADO

In [ ]:
import numpy as np

In [ ]:
#se crean dos arreglos (arrays)
a1 = np.arange(20).reshape(4,5)
a2 = np.random.randint(-10,10,size=(2,5))
a3 = np.arange(8).reshape(4,2)
print(a1)
print(a2)
print(a3)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 5  6 -4 -2  6]
 [-4  1 -4 -5  0]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [ ]:
#¿Què ocurre cuando corre este comando?
np.vstack((a1,a2))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 5,  6, -4, -2,  6],
       [-4,  1, -4, -5,  0]])

In [ ]:
#Corra los siguientes comandos
#np.hstack((a3,a1))
np.hstack((a1,a3))

array([[ 0,  1,  2,  3,  4,  0,  1],
       [ 5,  6,  7,  8,  9,  2,  3],
       [10, 11, 12, 13, 14,  4,  5],
       [15, 16, 17, 18, 19,  6,  7]])

In [ ]:
np.concatenate((a1,a3),axis=1)

array([[ 0,  1,  2,  3,  4,  0,  1],
       [ 5,  6,  7,  8,  9,  2,  3],
       [10, 11, 12, 13, 14,  4,  5],
       [15, 16, 17, 18, 19,  6,  7]])

###Juegue con las concatenaciones con arreglos de diferentes formas

In [23]:
import scipy  

In [26]:
#dir(np.linalg)

In [27]:
#dir(scipy.linalg)

In [28]:
#Para "aplanar" un arreglo
np.ravel(a1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
a = np.linspace(1,20,20)
a = a.astype(int)
a = a[np.newaxis,:]
a.shape

(1, 20)

####comandos estadìsticos

In [50]:
np.mean(a1)

9.5

In [55]:
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [57]:
np.mean(a1,axis =1)

array([ 2.,  7., 12., 17.])

In [58]:
np.var(a2,axis=1)

array([68.24, 24.56])

In [59]:
np.std(a2,axis=1)

array([8.26075057, 4.95580468])

In [64]:
x = np.array([[0, 2], [1, 4], [2, 6], [3,8]]).T
x

array([[0, 1, 2, 3],
       [2, 4, 6, 8]])

In [65]:
np.cov(x)

array([[1.66666667, 3.33333333],
       [3.33333333, 6.66666667]])

In [53]:
matriz =[[1,2,3],[-2,-4,-6],[8,16,24]]
a = np.array(matriz)
np.corrcoef(a)

array([[ 1., -1.,  1.],
       [-1.,  1., -1.],
       [ 1., -1.,  1.]])

In [54]:
np.cov(a)

array([[  1.,  -2.,   8.],
       [ -2.,   4., -16.],
       [  8., -16.,  64.]])

###productos entre arreglos

In [66]:
a = np.arange(5)
b = np.arange(20).reshape(4,5)


In [67]:
a,b

(array([0, 1, 2, 3, 4]),
 array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]))

In [68]:
a*b

array([[ 0,  1,  4,  9, 16],
       [ 0,  6, 14, 24, 36],
       [ 0, 11, 24, 39, 56],
       [ 0, 16, 34, 54, 76]])

In [70]:
b.dot(a)

array([ 30,  80, 130, 180])

In [72]:
a = np.arange(1,4)
b = np.arange(1,4)

a.dot(b)

14

In [ ]:
#a.shape

In [ ]:
#a[:,np.newaxis].shape

In [ ]:
#a[np.newaxis,:].shape

In [ ]:
##Vamos a cargar un archivo de Excel
#np.loadtxt()

<function numpy.load(file, mmap_mode=None, allow_pickle=False, fix_imports=True, encoding='ASCII')>